### ISSUE TITLE
Mirroring is not working when a large payload is posted 

### ISSUE THREAD

**Issue by mark-k-english** [haproxytech/spoa-mirror#6]
Using the documented procedures I've been able to successfully mirror small payloads that don't solicit a 100 status response or send a an expect:100-continue. This issue is easily reproduced by using curl and a payload that exceeds 16384.

**Comment by zaga00** [comment]
In order for the POST method to send a larger amount of data, a few modifications to the HAProxy configuration files need to be made.

In haproxy.cfg it is necessary to add tune.bufsize in the global section (in this example i will set it to 100kB; i.e., a size sufficient to allow POST data to be mirrored):

`global`
`tune.bufsize 102400`

The http-buffer-request option should be added to the 'frontend' part of the configuration:

`frontend spoe-test-frontend`
`option http-buffer-request`

Then, in spoe.cfg the max-frame-size should be increased (here it will be 100kB - 4B):

`[spoe-test]`
`max-frame-size 102396`

Finally, when running spoa-mirror, a parameter should be used to increase the max-frame size it uses:

`./src/spoa-mirror -m102396`

**Comment by amorellg** [comment]
Hi, thanks @zaga00 for the feedback, I have a similar issue and I was able to mirror POST requests with significant body sizes with the configuration you recommended.

However, is it possible to mirror these requests without buffering the entire body? which is imposed by the option `http-buffer-request`. I tried just removing it, but the body is not transferred at all to my mirror.

This is because I have an application where I need to mirror POST requests with body sizes significantly larger than 100Kb and I need to process the data as soon as they are received in my backend server, hence there is a hard requirement to avoid buffering the complete body.

Many thanks in advance.

**Comment by zaga00** [comment]
Hello @amorellg, I don't think there is any other way of mirroring these requests without buffering all the content.  Currently, SPOP does not support a different mode.  For more information you can contact the HAProxy mailing list at haproxy@formilux.org.

**Comment by in4mer** [comment]
I've a bit of an outlier situation.. using HTTP for JSON RPC, and seeing POST payloads somewhere around 1MB in stage (10MB in prod), spoa-mirror is pretty quickly grabbing all available memory and inducing OOMs.  The tune.bufsize is 2^24 (16MB) in haproxy.cfg, and both the mirror.cfg and the program section in haproxy.cfg set max_buffer_size to 2^24 - 4.

I'm leaning towards compiling spoa-mirror with debug support and inducing debug logs, but I'm wondering if this is still maintained or an interest.
